# Cookstyle (rubocop) todo:

Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'recipes/app_lb.rb'

Lint/UselessAssignment:
  Exclude:
    - 'spec/recipes/lb_spec.rb'

Metrics/BlockNesting:
  Max: 5

Style/GuardClause:
  Exclude:
    - 'providers/default.rb'
